import { BrowserRouter, Route, Routes } from 'react-router-dom'
import Layout from './components/Layout'
import ProtectedRoute from './components/auth/ProtectedRoute'
import { AuthProvider } from './context/AuthContext'
import AuthPage from './pages/AuthPage'
import Compare from './pages/Compare'
import Dashboard from './pages/Dashboard'
import Demo from './pages/Demo'
import Discover from './pages/Discover'
import Evaluation from './pages/Evaluation'
import ImportData from './pages/ImportData'
import HateList from './pages/HateList'
import Landing from './pages/Landing'
import MovieDetail from './pages/MovieDetail'
import Roulette from './pages/Roulette'
import SearchPage from './pages/SearchPage'
import Settings from './pages/Settings'
import Stats from './pages/Stats'
import TasteDNA from './pages/TasteDNA'
import WatchTonight from './pages/WatchTonight'
import Watchlist from './pages/Watchlist'

export default function App(){return <BrowserRouter><AuthProvider><Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<AuthPage mode="login"/>}/><Route path="/register" element={<AuthPage mode="register"/>}/><Route path="/demo" element={<Demo/>}/><Route element={<ProtectedRoute/>}><Route element={<Layout/>}><Route path="dashboard" element={<Dashboard/>}/><Route path="discover" element={<Discover/>}/><Route path="tonight" element={<WatchTonight/>}/><Route path="watchlist" element={<Watchlist/>}/><Route path="taste-dna" element={<TasteDNA/>}/><Route path="stats" element={<Stats/>}/><Route path="evaluation" element={<Evaluation/>}/><Route path="hate" element={<HateList/>}/><Route path="search" element={<SearchPage/>}/><Route path="compare" element={<Compare/>}/><Route path="roulette" element={<Roulette/>}/><Route path="import" element={<ImportData/>}/><Route path="settings" element={<Settings/>}/><Route path="movies/:id" element={<MovieDetail/>}/></Route></Route><Route path="*" element={<Landing/>}/></Routes></AuthProvider></BrowserRouter>}
